### ISSUE TITLE
API Error 400 - Bad Request

### ISSUE THREAD

**Issue by Kasherpete** [ivangabriele/mistralai-client-rs#13]
Hello, I just tried to use this library but it's giving me the following error:

```
thread 'main' panicked at src/main.rs:37:62:
called `Result::unwrap()` on an `Err` value: ApiError { message: "{\"object\":\"error\",\"message\":\"Input should be a valid dictionary or object to extract fields from\",\"type\":\"invalid_request_error\",\"param\":null,\"code\":null}: 400 Bad Request" }
```

Any idea what could be causing it? It works just fine in Python so I know it isn't an account issue. I'm literally just using the chat example from the README with a couple extra lines of code for the environment variables, but I could provide my code if you need a reference and can't reproduce it. This is my very first time dealing with Rust, any idea what could be causing it?

**Comment by ivangabriele** [comment]
Hi,

Indeed, sharing the code you used so I can try to reproduce your issue would be helpful :).

**Comment by francois-caddet** [comment]
Hello

Exactly the same issue here.
I tryed the chat_async example. I'll try the others but I suppose that will give me the same.
I'm on NixOS. I'm not convinced that it's part of the issue but I'll try on an other system tomorow and if it works I'll come back here.
The most strange with this is that a couple of months before it was working well.
Mistral made a few updates in the API recently but I don't see anything that could cause this issue for now.

**Comment by Kasherpete** [comment]
> Hi,
> 
> Indeed, sharing the code you used so I can try to reproduce your issue would be helpful :).

I think I've already deleted what I had since it was just the chat example from the README. Does it work for you right now?

**Comment by francois-caddet** [comment]
For me the same, it's a copy paste of the async_chat example.

EDIT: I just tried to run `cargo run --example chat_async` exporting previously the `MISTRAL_API_KEY` env variable. It Does not work on my Ubuntu 22.04 nor on my NixOS 24.11 unstable. So I supose that something is broken but I checked your code and Have no idea where could be the issue...

**Comment by francois-caddet** [comment]
Fixed ;)

almost on my side.

Actualy, the issue com from the headers you add @ivangabriele in the `build_request`. I droped the `Accept` and `Content-Type` ones and it works.
In fact, the `Content-Type` is useless an may be conflicting with reqwest internal stufs which add it since you use the `.json` method on the client builder if I rember well.
For the `Accept` I'm not sure but almost the same, you call `.json` and it's a json API so I thinks it's safe to drop both of these headers.
The other option to investigate is to use the method `reqwest::Client::headers` instead of the `header` one. Maybe the `header` method is not an insert function but can only put a header and break everything after... song very strange anyway.

I'll try to fork and open a PR using the first option I proposed in the weekend. Feel free to try another one :)

EDIT: After an other test, you can keep the `Accept` header if you prefer. Does not cause issues.

**Comment by ivangabriele** [comment]
This is a strange issue but indeed `Content-Type` is useless anyway so I merged your PR. My main OS is Ubuntu and I didn't have the issue when testing but I haven't worked on this repo for 6 something weeks.

Thank for the catch, the resolution and the PR!
